Hw 2 count det
Lenin22/made-cpp-2020-hw pull request #3
Opened 2020-09-29 18:26 UTC by Lenin22

Я не совсем разобрался как именно делать пулл реквест, возможно, я повторно Вам шлю одно и то же

2020-10-01 12:54 UTC, xterrafunny requested changes

2020-10-01 12:54 UTC, xterrafunny commented on count_det/src/main.s
> +ldr r1, [r0, #0]
Необходимо положить на стек значения регистров `r4-...`, значения которых изменяются во время работы функции, так как они могли хранить данные вне функции

2020-10-01 12:54 UTC, xterrafunny commented on count_det/src/main.s
> +bx lr
А здесь необходимо сделать `pop` со стека

2020-10-06 18:25 UTC, Lenin22 commented
Проверьте, пожалуйста. Я как только исправил в чат написал, возможно, и сюда стоит

2020-10-08 18:09 UTC, merged