Proj 1 vector operations
Lenin22/made-cpp-2020-hw pull request #5
Opened 2020-10-05 12:17 UTC by Lenin22

vector operations done

2020-10-16 17:56 UTC, SweetWeakness requested changes
в целом все ок

2020-10-16 17:56 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +	double ERR_EPS = 1e-7;
табуляция запрещена

2020-10-16 17:56 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +		return false;
но только мы договорились что это все таки true (нулевой вектор сонаправлен всем)

2020-10-16 17:56 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +		return (1 - cos2fi < ERR_EPS) && (dot > 0);
у вас уже написано это в коллинеарности
используйте ее

2020-10-16 17:56 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +			start = false;
в каждой итерации будет лишнее обращение к start - проще тогда cout << ... << " ";

2020-10-16 17:56 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +			data[data.size() - 1 - i] = buf;
std::swap

2020-10-24 08:56 UTC, Lenin22 commented
Исправил замечания

2020-10-31 20:28 UTC, merged